### ISSUE TITLE
Add ability to use more variables in plots where currently only focus variables are allowed.

### ISSUE THREAD

**Issue by berryni** [el-meyer/airship#127]
Commonly I want to add something like Outcome or LastInterim to a plot as a color or x-axis in a boxplot, and it's not currently possible. Would be great to be able to either specify them as "input" variables that could then be focus variables or just allow "integer" or "factor" valued variables to be used in those input boxes during plot creation. I prefer the latter solution if possible?

**Comment by el-meyer** [comment]
We currently plan to keep focus variables only for simulation input variables, but allow e.g. output variables as aesthetics in the plots. 

This means the following can happen:

In the dataset I am investigating, "Successes" ranges from 0-5
![image](https://github.com/el-meyer/airship/assets/73820185/621bf7ab-f2b8-4e5b-9dfd-0598529bcbb1)

However, since "Successes" is not an input variable, when chosen as an aesthetic, it keeps the dataset filtered according to what was set in focus variables. 

![image](https://github.com/el-meyer/airship/assets/73820185/4e4ac6d2-da4e-458d-8238-af603c226e4d)

@berryni Is this intended behviour?

**Comment by berryni** [comment]
I think this makes sense as intended behavior? Obviously the plot isn't very informative, but it is what I would expect to happen. I think it could be a bit confusing at first if you don't realize why there is only one level of Successes. Not sure I have a good way to notify the user that there is only 1 level to a used variable.

**Comment by el-meyer** [comment]
I agree it makes sense as intended behviour. It forces users to pay more attention to the setting (or not setting) of default values and as such leads to them better understanding the data. 

I will continue implementing it this way and then we can re-evaluate later.

**Comment by el-meyer** [comment]
The previous commit adds a button that allows users to choose if they want to specify focus variables or not. It then also implements the requested feature for the Boxplot Tab. 

@berryni Maybe you could check it out and let me know what you think. If you like it, I will implement it for the rest of the tabs.
